name: Python CI

on: [push, pull_request]

jobs:
 run-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run the script
        run: python login.py 
